baseURL = 'https://edenkaplinsky.github.io/portfolio/'
languageCode = 'en-us'
title = 'Eden Kaplinsky'
theme = 'ananke'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
